---

- name: Start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Enable NAT 
  ansible.builtin.command: "firewall-cmd --zone=public --add-masquerade --permanent"

- name: Firewall rules for warewulf services
  ansible.builtin.command: "firewall-cmd --zone=public --permanent --add-service={{ item }}"
  with_items: "{{ warewulf_services }}"

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
