---

- name: Install warewulf 
  ansible.builtin.package:
    name: "{{ ww_rpm_url }}"
    disable_gpg_check: true
    state: present

- name: Place warewulf.conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/warewulf/warewulf.conf"
    dest: /etc/warewulf/warewulf.conf
    mode: preserve
  register: ww_conf_status

- name: Node tasks
  tags: add_nodes
  block:
  - name: Place nodes.conf
    ansible.builtin.copy:
      src: "{{ role_path }}/files/etc/warewulf/nodes.conf"
      dest: /etc/warewulf/nodes.conf
      mode: preserve
    register: nodes_conf_status

  - name: Build node overlays
    ansible.builtin.shell: >
      wwctl overlay build
    when: nodes_conf_status.changed

  - name: Pull warewulfd status
    ansible.builtin.shell: >
      systemctl status warewulfd | grep -oE "running|inactive"
    register: warewulfd_status
    when: nodes_conf_status.changed

  - name: Reload warewulfd
    ansible.builtin.service:
      name: warewulfd
      state: reloaded
    when: (nodes_conf_status.changed and warewulfd_status.stdout == "running")

- name: Start and enble warewulfd
  ansible.builtin.service:
    name: warewulfd
    state: started
    enabled: true

- name: Warewulf configure all services
  ansible.builtin.shell: >
    wwctl configure --all
  when: ww_conf_status.changed
